src/Entity/Notice.php
<?php

namespace App\Entity;

use App\Repository\NoticeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=NoticeRepository::class)
 */
class Notice
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToMany(targetEntity=NewsType::class, inversedBy="notices" , cascade={"persist"})
     */
    private $type;

    /**
     * @ORM\ManyToOne(targetEntity=Specialty::class, inversedBy="notices", cascade={"persist"})
     */
    private $specialty;

    /**
     * @ORM\ManyToOne(targetEntity=Products::class, inversedBy="notices" , cascade={"persist"})
     */
    private $products;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;


    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $link;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_active;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image_alt;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image_title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $year;


    public function __construct()
    {
        $this->category = new ArrayCollection();
        $this->type = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getType()
    {

        return  $this->type;
    }

    public function setType($type): self
    {
        $this->type = $type;

        return $this;
    }

    public function addType(?NewsType $type): self
    {
        $this->type[] = $type;

        return $this;
    }


    public function getSpecialty(): ?Specialty
    {
        $this->specialty = $this->specialty;
        return  $this->specialty;
    }

    public function setSpecialty(?Specialty $specialty): self
    {
        $this->specialty = $specialty;

        return $this;
    }


    public function getProducts(): ?Products
    {
        $this->products = $this->products;
        return  $this->products;
    }

    public function setProducts(?Products $products = null): self
    {
        $this->products = $products;

        return $this;
    }



    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getLink(): ?string
    {
        return $this->link;
    }

    public function setLink(string $link): self
    {
        $this->link = $link;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(bool $is_active): self
    {
        $this->is_active = $is_active;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getImageAlt(): ?string
    {
        return $this->image_alt;
    }

    public function setImageAlt(string $image_alt): self
    {
        $this->image_alt = $image_alt;

        return $this;
    }

    public function getImageTitle(): ?string
    {
        return $this->image_title;
    }

    public function setImageTitle(string $image_title): self
    {
        $this->image_title = $image_title;

        return $this;
    }


    public function getYear(): ?string
    {
        return $this->year;
    }

    public function setYear(?string $year): self
    {
        $this->year = $year;

        return $this;
    }
}

src/Controller/Front/AboutController.php
<?php

namespace App\Controller\Front;


use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Cookie;

class AboutController extends AbstractController
{
    /**
     * @Route("/quem-somos", name="quem-somos")
     */
    public function index(Request $request): Response
    {
        return $this->render('front/quem-somos/index.html.twig', []);
    }
}

src/Controller/Front/AtuacaoController.php
<?php

namespace App\Controller\Front;


use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AtuacaoController extends AbstractController
{
    /**
     * @Route("/area-de-atuacao", name="area-de-atuacao")
     */
    public function index(): Response
    {
        return $this->render('front/area-de-atuacao/index.html.twig', [
            'controller_name' => 'AtuacaoController',
        ]);
    }
}

src/Controller/Front/ContatoController.php
<?php

namespace App\Controller\Front;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use App\Entity\Contact;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;
use Symfony\Component\Mime\Address;
use Symfony\Component\Routing\Annotation\Route;

class ContatoController extends AbstractController
{
    /**
     * @Route("/contato", name="contato")
     */
    public function index(): Response
    {
        return $this->render('front/contato/index.html.twig', [
            'controller_name' => 'ContatoController',
        ]);
    }


    /**
     * @Route("/problemas-na-navegacao", name="contato_problemas")
     */
    public function contatoProblemas(Request $request, MailerInterface $mailer)
    {
        $message = null;

        if ($request->isMethod('get')) {
            return $this->render('front/contato/problemas.html.twig', [
                'status' => false,
                'message' => $message
            ]);
        }
      
        if ($request->request->get('contact')) {
            $contact = $request->request->get('contact');
            $name = isset($contact['name']) ? $contact['name'] : null;
            $ddd = isset($contact['ddd']) ? $contact['ddd'] : null;
            $phone = isset($contact['phone']) ? $contact['phone'] : null;
            $email = isset($contact['email']) ? $contact['email'] : null;
            $message = isset($contact['message']) ? $contact['message'] : null;
            
            $errors = [];

            if (!$name) {
                $errors['name'] = 'Nome é obrigatório';
            }

            if (!$ddd) {
                $errors['ddd'] = 'DDD é obrigatório';
            } else {
                // if (strlen($ddd) < 2) { //contando com as maskaras
                //     $errors['ddd'] = "Celular inválido";
                // }
            }

            if (!$phone) {
                $errors['phone'] = 'Celular é obrigatório';
            } else {
               // if ($phone) {
                                  
                    // if (strlen($phone) < 9) { //contando com as maskaras
                    //     $errors['cellphone'] = "Celular inválido";
                    // }
                //}  
            }

            if (!$email) {
                $errors['email'] = 'E-mail é obrigatório';
            }

            if (!$name) {
                $errors['message'] = 'Comentario é obrigatório';
            }

            $secret = '6LcgV24eAAAAAJUL9GHzfE6zTa1cl-cfR-HoUtO1';  // check if reCaptcha has been validated by Google     
            $captchaId = $request->request->get('g-recaptcha-response'); /** REcaptcha */
            $responseCaptcha = json_decode(file_get_contents('https://www.google.com/recaptcha/api/siteverify?secret='.$secret.'&response='.$captchaId)); //send recaptcha
            
            if ($responseCaptcha->success == true) {
                         
            } else {
               $errors['recaptcha'] = "Selecione o recaptcha é obrigatório";
            }

            //dump($errors); die();


            if (count($errors) > 0) {
                return $this->render('front/contato/problemas.html.twig', [
                    'status' => false,
                    'errors' => $errors,
                    'message' => 'Preencha os campos obrigatórios'
                ]);
            }
            
            $c = new Contact();

            $c->setName($contact['name']);
            $c->setDdd($contact['ddd']);
            $c->setPhone($contact['phone']);
            $c->setEmail($contact['email']);
            $c->setMessage($contact['message']);
            $c->setCreatedAt(new \DateTime());

            $em = $this->getDoctrine()->getManager();
            $em->persist($c);
            $em->flush();

            $response = $this->sendContact($c, $mailer, 'suporteportal@mantecorp.com.br', 'front/component/email.html.twig');
            
            if ($response) {
                $message = 'Obrigado, seu contato foi enviado com sucesso. Em breve enviaremos uma resposta.';
            }

            return $this->render('front/contato/problemas.html.twig', [
                'status' => true,
                'message' => $message
            ]);
        }
        
    }

    private function sendContact($contact, $mailer, $to,  $render)
    {


        $email = (new Email())
            ->from(new Address('portalmantecorpfarmasa@gmail.com', 'Contato Mantecorp Farmasa'))
            ->to($to)
            ->addBcc('ana.morales@cappuccinodigital.com.br')
            //->replyTo($contact->getEmail())
            ->priority(Email::PRIORITY_HIGH)
            ->subject('')
            ->html($this->renderView(
                $render,
                ['contact' => $contact]
            ));

        $mailer->send($email);
        return true;
    }
}

src/Controller/Front/DoctorsController.php
<?php

namespace App\Controller\Front;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DoctorsController extends AbstractController
{
    /**
     * @Route("/medicos/material/clg-video01", name="front_doctors")
     */
    public function index(): Response
    {
        return $this->render('front/doctors/index.html.twig', [
            'controller_name' => 'DoctorsController',
        ]);
    }
}

src/Controller/Front/EducacaoMedicaController.php
<?php

namespace App\Controller\Front;


use App\Entity\Course;

use App\Service\EadBoxService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Cookie;


class EducacaoMedicaController extends AbstractController
{
    /**
     * @Route("/educacao-medica", name="educacao-medica")
     */
    public function index(Request $request, EadBoxService $ead_box_service): Response
    {
        //validação para evitar roubo de dados confidenciais 
        if ($request->query->has('q') || $request->query->has('s')) {
            throw $this->createNotFoundException('A página não foi encontrada');
        }

        if (!$this->container->get('security.authorization_checker')->isGranted('IS_AUTHENTICATED_FULLY')) {
            /** Gravando a referencia do conteúdo */
            $url_reference = $request->getUri();
            $response = $this->redirectToRoute('login');
            $response->headers->setCookie(new Cookie('_referenceURL', $url_reference));
            return $response;
            /*** END  */
        }

        $user = $this->getUser();

        $em = $this->getDoctrine()->getManager();
        $q = $em->getRepository('App:Course')->createQueryBuilder('c');
        
        if ($request->request->has('e')) {
            if ($request->request->get('s')) {
                $specialty = $em->getRepository('App:Specialty')->findOneBy(['id' => $request->request->get('s')]);

                             $q->where('c.specialty = :specialty')
                                ->setParameter('specialty', $specialty);
            }

            if ($request->request->get('t')) {
                $education = $em->getRepository('App:Education')->findOneBy(['id' => $request->request->get('t')]);
               
                            $q->andWhere('c.type = :education')
                                ->setParameter('education', $education);
            }

            if (trim($request->request->get('q'))) {
                    $q->andWhere('c.name LIKE :search or c.resume LIKE :search')
                    ->setParameter('search', '%' .$request->request->get('q').'%');
            }
        } else {
            $user_ead = $em->getRepository('App:UserEad')->findOneBy(['email' => $user->getEmailEadbox()]);
        
            if ($user_ead) { 
                if ($user_ead->getPassword() != $user->getPassword()) {
                    //EadBox update da senha
                    $ead_box_service->updateUser($user);
                }
            }
        }

        $courses = $q->getQuery()->getResult();
    
        $specialty = $em->getRepository('App:Specialty')->findAll();
        $educations = $em->getRepository('App:Education')->findAll();

        
        return $this->render('front/educacao-medica/index.html.twig', [
            'controller_name' => 'EducacaoMedicaController',
            'courses' => $courses,
            'specialties' => $specialty,
            'educations' => $educations,
            'filtro' => $request->request->has('e') ? true : false
        ]);
    }

    /**
     * @Route("/educacao-medica/busca", name="educacao_medica_filtro_especialidade")
     */
    public function buscaPorEspecialidade(Request $request): Response
    {
        $em = $this->getDoctrine()->getManager();

        $courses = $em->getRepository('App:Course')->findBySpecialty($request->request->get("s"));

        return new JsonResponse([
            'response' => $courses,
        ]);
    }

    /**
     * @Route("/educacao-medica/eadbox", name="educacao-medica-eadbox")
     */
    public function eadbox(Request $request, EadBoxService $ead_box_service): Response
    {
        if (!$this->container->get('security.authorization_checker')->isGranted('IS_AUTHENTICATED_FULLY')) {
            /** Gravando a referencia do conteúdo */
            $url_reference = $request->getUri();
            $response = $this->redirectToRoute('login');
            $response->headers->setCookie(new Cookie('_referenceURL', $url_reference));
            return $response;
            /*** END  */
        }

        $user = $this->getUser();

        $access_eadbox = $ead_box_service->accessEadbox($user);
       
        if ($access_eadbox['status']) {
            $url = $access_eadbox['url'];
            return $this->redirect($url);
        }

        return $this->redirectToRoute('educacao-medica');
    }
}

src/Controller/Front/NotFoundController.php
<?php

namespace App\Controller\Front;


use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class NotFoundController extends AbstractController
{
    /**
     * @Route("/404", name="404")
     */
    public function show(): Response
    {
        return $this->render('front/404/index.html.twig', [
            'controller_name' => 'NotFoundController',
        ]);
    }
}

templates/front/seu-paciente/index.html.twig
{% extends 'front/base.html.twig' %} {% block title %}Você e seu Paciente{% endblock %} {% block body %}
<style>
    .pagination {
        justify-content: center;
    }
</style>
<div class="you-and-patient">
    <div class="container">
        <div class="bg-top-patient sem-prescricao">
            <figure class="seta hidden-xs">
                <img class="" src="{{ asset('_dist/image/template/ativo1.png') }}" alt="Setas" title="Setas">
            </figure>
            <div class="bg-top-img-1 bg-top-img"></div>
        </div>
    </div>
    <section class="home-top container" id="section">
        <div class="home-top-text">
            <div class="lettering-area">
                <img class="" src="{{
                  asset('_dist/image/template/lettering-voce.png') }}" alt="Área Médica Mantecorp" title="Área Médica Mantecorp">
            </div>
            <div class="img-patient">
                <img class="" src="{{
                  asset('_dist/image/template/your-patient1.png') }}" alt="Área Médica Mantecorp" title="Área Médica Mantecorp">
            </div>
            <div class="lettering-medica">
                <img class="" src="{{
                  asset('_dist/image/template/lettering-patient.png') }}" alt="Área Médica Mantecorp" title="Área Médica Mantecorp">
            </div>
        </div>
    </section>
    <section class="your-patient container">
        <h1>VOCÊ e <br> <b>SEU PACIENTE</b></h1>
        <p>Você e Seu Paciente é uma área dedicada a médicos com o intuito de oferecer conteúdo de qualidade sobre saúde, facilitando o entendimento dos mais variados assuntos relacionados ao tema por parte de seus pacientes.</p>
        <p>São vídeos, artigos e apresentações que podem ser compartilhados com o intuito de espalhar conhecimento e responder dúvidas comuns. Estamos produzindo novos conteúdos e, em breve, teremos uma página repleta de informações, divididas por especialidades.</p>
        <p>Aproveite!</p>
    </section>
</div>
<div class="container  medical-specialties">
    <form id="form-your-patients" action="{{ path('voce-e-o-seu-paciente') }}" method="post">
        <input type="hidden" name="e"/>
        <ul class="search-medical-education">
            <li>
                <a>
                    <select name="s" class="search-field" id="filtro_specialty">
                        <option value="">Filtro por Especialidade</option>
                        {% for specialty in specialties %}
                            <option value="{{ specialty.id }}" {{ app.request.get('s') == specialty.id ? 'selected' : '' }}>{{ specialty.specialty }}</option>
                        {% endfor %}
                    </select>
                </a>
            </li>
            <li id="limpar_filtro"><a href="{{ path('voce-e-o-seu-paciente') }}">Limpar filtro  &nbsp;&nbsp;<i class="fas fa-times"></i></a></i>
            </li>
        </ul>
    </form>
</div>

<div id="seu_paciente">
    {% if products|length > 0 %}
        {% for product in products %}
            <div class="your-patient-materials container">
                <div class="row right-flex-end">
                    <div class="col-12 col-sm-5 col-md-5 col-lg-5">
                        <div class="your-patient-img">
                            <img src="{{ asset(product.image) }}" alt="{{ product.imageTitle }}" title="{{ product.imageTitle }}">
                        </div>

                        {% set files = yourPatient(product, 'File') %}

                        {% if files|length > 0 %}
                            {% for file in files %}
                                <div class="your-patient-font-type">
                                    <h3>{{ file.titleM|raw }}</h3>
                                    {{ file.resumeM|raw }}
                                    {% if file.file %}
                                        <a href="{{ file.file }}" download> <img src="{{ asset('_dist/image/template/circle-down.png') }}"></i>&nbsp;&nbsp; Baixar</a>
                                    {% endif %}
                                </div>
                            {% endfor %}
                        
                        {% endif %}

                        <div class="angle-down">
                            <img src="{{ asset('_dist/image/template/angle-down.png') }}">
                        </div>
                    </div>

                    {% set videos = yourPatient(product, 'Video') %}
                    
                    <div class="col-12 col-sm-7 col-md-7 col-lg-7 ">
                        {% if videos|length > 0 %}
                            <div id="arrow-prev1" class="arrow"></div>
                        {% endif %}
                        <div class="responsive1">
                            {% if videos|length > 0 %}
                                {% for video in videos %}
                                    <div class="slide-font-type">
                                        {{ video.video|raw }}
                                        <h3>{{ video.titleV|raw }}</h3>
                                        {{ video.resumeV|raw }}
                                    </div>
                                {% endfor %}
                            {% endif %}

                            {# 
                             <div class="slide-font-type">
                                <img src="https://areamedica.novo.mantecorp.webcenter.net.br/_dist/image/template/thumb-video.png">

                                    <h3> Título do vídeo disponíveis </h3>
                                    <p>
                                        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Rem minima quae cum non odit tempore? Quae unde et quos vitae?
                                    </p>
                                </div>
                            <div class="slide-font-type">
                                 <img src="{{ asset('_dist/image/template/thumb-video.png') }}">

                                <h3> Título do vídeo disponíveis </h3>
                                <p>
                                    Lorem ipsum, dolor sit amet consectetur adipisicing elit. Rem minima quae cum non odit tempore? Quae unde et quos vitae?
                                </p>
                            </div> #}

                        </div>
                        {% if videos|length > 0 %}
                            <div id="arrow-next1" class="arrow"></div>
                        {% endif %}
                    </div>
                </div>
                <hr>
            </div>
        {% endfor %}
    {% endif %}
   
</div>

<div class="bolinha-2-bottom-left-paciente paralax hidden-xs">
  <img src="{{ asset('_dist/image/template/curva-bottom.png') }}" alt="Bolinha" title="Bolinha">
</div>
<div class="paralax bolinha-1-bottom-left-paciente hidden-xs">
    <img src="{{ asset('_dist/image/template/curva-2.png') }}" alt="Bolinha" title="Bolinha">
</div>
<div class="paralax element-2-midle-right-paciente hidden-xs">
    <img src="{{ asset('_dist/image/template/curva-4.png') }}" alt="Bolinha" title="Bolinha">
</div>
{% endblock %}

{% block javascripts %}
<script>
    $(document).ready(function() {
        $('#form-your-patients select').on('change', function(e) { 
            $('#form-your-patients').submit()
        })
    })
</script>
{% endblock %}