src/Entity/Menu.php
<?php

namespace App\Entity;

use App\Repository\MenuRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MenuRepository::class)
 */
class Menu
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $url;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_active;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_caterer = false;

    /**
     * @ORM\OneToMany(targetEntity=UserAcess::class, mappedBy="menus")
     */
    private $userAcesses;

    /**
     * @ORM\ManyToOne(targetEntity=MenuCategory::class, inversedBy="menus")
     */
    private $menu_category;

    public function __construct()
    {
        $this->userAcesses = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(bool $is_active): self
    {
        $this->is_active = $is_active;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection|UserAcess[]
     */
    public function getUserAcesses(): Collection
    {
        return $this->userAcesses;
    }

    public function addUserAcess(UserAcess $userAcess): self
    {
        if (!$this->userAcesses->contains($userAcess)) {
            $this->userAcesses[] = $userAcess;
            $userAcess->setMenus($this);
        }

        return $this;
    }

    public function removeUserAcess(UserAcess $userAcess): self
    {
        if ($this->userAcesses->contains($userAcess)) {
            $this->userAcesses->removeElement($userAcess);
            // set the owning side to null (unless already changed)
            if ($userAcess->getMenus() === $this) {
                $userAcess->setMenus(null);
            }
        }

        return $this;
    }

    public function getMenuCategory(): ?MenuCategory
    {
        return $this->menu_category;
    }

    public function setMenuCategory(?MenuCategory $menu_category): self
    {
        $this->menu_category = $menu_category;

        return $this;
    }

    public function getIsCaterer(): ?bool
    {
        return $this->is_caterer;
    }

    public function setIsCaterer(bool $is_caterer): self
    {
        $this->is_caterer = $is_caterer;

        return $this;
    }
}

src/Controller/Front/AboutController.php
<?php

namespace App\Controller\Front;


use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Cookie;

class AboutController extends AbstractController
{
    /**
     * @Route("/quem-somos", name="quem-somos")
     */
    public function index(Request $request): Response
    {
        return $this->render('front/quem-somos/index.html.twig', []);
    }
}

src/Controller/Front/AtuacaoController.php
<?php

namespace App\Controller\Front;


use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AtuacaoController extends AbstractController
{
    /**
     * @Route("/area-de-atuacao", name="area-de-atuacao")
     */
    public function index(): Response
    {
        return $this->render('front/area-de-atuacao/index.html.twig', [
            'controller_name' => 'AtuacaoController',
        ]);
    }
}

src/Controller/Front/ContatoController.php
<?php

namespace App\Controller\Front;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use App\Entity\Contact;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;
use Symfony\Component\Mime\Address;
use Symfony\Component\Routing\Annotation\Route;

class ContatoController extends AbstractController
{
    /**
     * @Route("/contato", name="contato")
     */
    public function index(): Response
    {
        return $this->render('front/contato/index.html.twig', [
            'controller_name' => 'ContatoController',
        ]);
    }


    /**
     * @Route("/problemas-na-navegacao", name="contato_problemas")
     */
    public function contatoProblemas(Request $request, MailerInterface $mailer)
    {
        $message = null;

        if ($request->isMethod('get')) {
            return $this->render('front/contato/problemas.html.twig', [
                'status' => false,
                'message' => $message
            ]);
        }
      
        if ($request->request->get('contact')) {
            $contact = $request->request->get('contact');
            $name = isset($contact['name']) ? $contact['name'] : null;
            $ddd = isset($contact['ddd']) ? $contact['ddd'] : null;
            $phone = isset($contact['phone']) ? $contact['phone'] : null;
            $email = isset($contact['email']) ? $contact['email'] : null;
            $message = isset($contact['message']) ? $contact['message'] : null;
            
            $errors = [];

            if (!$name) {
                $errors['name'] = 'Nome é obrigatório';
            }

            if (!$ddd) {
                $errors['ddd'] = 'DDD é obrigatório';
            } else {
                // if (strlen($ddd) < 2) { //contando com as maskaras
                //     $errors['ddd'] = "Celular inválido";
                // }
            }

            if (!$phone) {
                $errors['phone'] = 'Celular é obrigatório';
            } else {
               // if ($phone) {
                                  
                    // if (strlen($phone) < 9) { //contando com as maskaras
                    //     $errors['cellphone'] = "Celular inválido";
                    // }
                //}  
            }

            if (!$email) {
                $errors['email'] = 'E-mail é obrigatório';
            }

            if (!$name) {
                $errors['message'] = 'Comentario é obrigatório';
            }

            $secret = '6LcgV24eAAAAAJUL9GHzfE6zTa1cl-cfR-HoUtO1';  // check if reCaptcha has been validated by Google     
            $captchaId = $request->request->get('g-recaptcha-response'); /** REcaptcha */
            $responseCaptcha = json_decode(file_get_contents('https://www.google.com/recaptcha/api/siteverify?secret='.$secret.'&response='.$captchaId)); //send recaptcha
            
            if ($responseCaptcha->success == true) {
                         
            } else {
               $errors['recaptcha'] = "Selecione o recaptcha é obrigatório";
            }

            //dump($errors); die();


            if (count($errors) > 0) {
                return $this->render('front/contato/problemas.html.twig', [
                    'status' => false,
                    'errors' => $errors,
                    'message' => 'Preencha os campos obrigatórios'
                ]);
            }
            
            $c = new Contact();

            $c->setName($contact['name']);
            $c->setDdd($contact['ddd']);
            $c->setPhone($contact['phone']);
            $c->setEmail($contact['email']);
            $c->setMessage($contact['message']);
            $c->setCreatedAt(new \DateTime());

            $em = $this->getDoctrine()->getManager();
            $em->persist($c);
            $em->flush();

            $response = $this->sendContact($c, $mailer, 'suporteportal@mantecorp.com.br', 'front/component/email.html.twig');
            
            if ($response) {
                $message = 'Obrigado, seu contato foi enviado com sucesso. Em breve enviaremos uma resposta.';
            }

            return $this->render('front/contato/problemas.html.twig', [
                'status' => true,
                'message' => $message
            ]);
        }
        
    }

    private function sendContact($contact, $mailer, $to,  $render)
    {


        $email = (new Email())
            ->from(new Address('portalmantecorpfarmasa@gmail.com', 'Contato Mantecorp Farmasa'))
            ->to($to)
            ->addBcc('ana.morales@cappuccinodigital.com.br')
            //->replyTo($contact->getEmail())
            ->priority(Email::PRIORITY_HIGH)
            ->subject('')
            ->html($this->renderView(
                $render,
                ['contact' => $contact]
            ));

        $mailer->send($email);
        return true;
    }
}

src/Controller/Front/DoctorsController.php
<?php

namespace App\Controller\Front;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DoctorsController extends AbstractController
{
    /**
     * @Route("/medicos/material/clg-video01", name="front_doctors")
     */
    public function index(): Response
    {
        return $this->render('front/doctors/index.html.twig', [
            'controller_name' => 'DoctorsController',
        ]);
    }
}

src/Controller/Front/EducacaoMedicaController.php
<?php

namespace App\Controller\Front;


use App\Entity\Course;

use App\Service\EadBoxService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Cookie;


class EducacaoMedicaController extends AbstractController
{
    /**
     * @Route("/educacao-medica", name="educacao-medica")
     */
    public function index(Request $request, EadBoxService $ead_box_service): Response
    {
        //validação para evitar roubo de dados confidenciais 
        if ($request->query->has('q') || $request->query->has('s')) {
            throw $this->createNotFoundException('A página não foi encontrada');
        }

        if (!$this->container->get('security.authorization_checker')->isGranted('IS_AUTHENTICATED_FULLY')) {
            /** Gravando a referencia do conteúdo */
            $url_reference = $request->getUri();
            $response = $this->redirectToRoute('login');
            $response->headers->setCookie(new Cookie('_referenceURL', $url_reference));
            return $response;
            /*** END  */
        }

        $user = $this->getUser();

        $em = $this->getDoctrine()->getManager();
        $q = $em->getRepository('App:Course')->createQueryBuilder('c');
        
        if ($request->request->has('e')) {
            if ($request->request->get('s')) {
                $specialty = $em->getRepository('App:Specialty')->findOneBy(['id' => $request->request->get('s')]);

                             $q->where('c.specialty = :specialty')
                                ->setParameter('specialty', $specialty);
            }

            if ($request->request->get('t')) {
                $education = $em->getRepository('App:Education')->findOneBy(['id' => $request->request->get('t')]);
               
                            $q->andWhere('c.type = :education')
                                ->setParameter('education', $education);
            }

            if (trim($request->request->get('q'))) {
                    $q->andWhere('c.name LIKE :search or c.resume LIKE :search')
                    ->setParameter('search', '%' .$request->request->get('q').'%');
            }
        } else {
            $user_ead = $em->getRepository('App:UserEad')->findOneBy(['email' => $user->getEmailEadbox()]);
        
            if ($user_ead) { 
                if ($user_ead->getPassword() != $user->getPassword()) {
                    //EadBox update da senha
                    $ead_box_service->updateUser($user);
                }
            }
        }

        $courses = $q->getQuery()->getResult();
    
        $specialty = $em->getRepository('App:Specialty')->findAll();
        $educations = $em->getRepository('App:Education')->findAll();

        
        return $this->render('front/educacao-medica/index.html.twig', [
            'controller_name' => 'EducacaoMedicaController',
            'courses' => $courses,
            'specialties' => $specialty,
            'educations' => $educations,
            'filtro' => $request->request->has('e') ? true : false
        ]);
    }

    /**
     * @Route("/educacao-medica/busca", name="educacao_medica_filtro_especialidade")
     */
    public function buscaPorEspecialidade(Request $request): Response
    {
        $em = $this->getDoctrine()->getManager();

        $courses = $em->getRepository('App:Course')->findBySpecialty($request->request->get("s"));

        return new JsonResponse([
            'response' => $courses,
        ]);
    }

    /**
     * @Route("/educacao-medica/eadbox", name="educacao-medica-eadbox")
     */
    public function eadbox(Request $request, EadBoxService $ead_box_service): Response
    {
        if (!$this->container->get('security.authorization_checker')->isGranted('IS_AUTHENTICATED_FULLY')) {
            /** Gravando a referencia do conteúdo */
            $url_reference = $request->getUri();
            $response = $this->redirectToRoute('login');
            $response->headers->setCookie(new Cookie('_referenceURL', $url_reference));
            return $response;
            /*** END  */
        }

        $user = $this->getUser();

        $access_eadbox = $ead_box_service->accessEadbox($user);
       
        if ($access_eadbox['status']) {
            $url = $access_eadbox['url'];
            return $this->redirect($url);
        }

        return $this->redirectToRoute('educacao-medica');
    }
}

src/Controller/Front/FavoritosController.php
<?php

namespace App\Controller\Front;


use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Cookie;

class FavoritosController extends AbstractController
{
    /**
     * @Route("/favoritos", name="favorites")
     */
    public function index(Request $request): Response
    {
        if (!$this->container->get('security.authorization_checker')->isGranted('IS_AUTHENTICATED_FULLY')) {
            /** Gravando a referencia do conteúdo */
            $url_reference = $request->getUri();
            $response = $this->redirectToRoute('login');
            $response->headers->setCookie(new Cookie('_referenceURL', $url_reference));
            return $response;
            /*** END  */
        }

        $user = $this->getUser();
        $em = $this->getDoctrine()->getManager();
       
        $favorites = $em->getRepository('App:UserFavorite')->getUserFavoriteContent($user->getId());
      
        return $this->render('front/favoritos/index.html.twig', [
            'favorites' => $favorites,
        ]);
    }
}

src/Controller/Front/NotFoundController.php
<?php

namespace App\Controller\Front;


use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class NotFoundController extends AbstractController
{
    /**
     * @Route("/404", name="404")
     */
    public function show(): Response
    {
        return $this->render('front/404/index.html.twig', [
            'controller_name' => 'NotFoundController',
        ]);
    }
}

templates/front/favoritos/index.html.twig
{% extends 'front/base.html.twig' %} {% block title %}Favoritos{% endblock %} {% block body %}
 <div class="favoritos-page"> 
    <div class="container">
        <div class="bg-top sem-prescricao">
          <figure class="seta">
              <img class="" src="{{ asset('_dist/image/template/setas.png') }}" alt="Setas" title="Setas">
          </figure>
          <div class="bg-top-img-1 bg-top-img"></div>
        </div>
    </div>
    <div class="paralax element-1-top-left hidden-xs">
        <img src="{{ asset('_dist/image/template/curva-1.png') }}" alt="Bolinha" title="Bolinha">
    </div>
  </div>
  <div class="paralax element-2 hidden-xs">
        <img src="{{ asset('_dist/image/template/curva-2.png') }}" alt="Bolinha" title="Bolinha">
    </div>
  
  
  <div class="container favorite-title">
    <h1 class="events-button">Favoritos</h1>
  </div>
 {% if favorites|length > 0 %}
  <div class="container page-favorite">
    <div class="row">
      {% for favority in favorites %}
          {% set object = favority.object %}
          {% set contents = favority.contents %}
          {% set contents_type = favority.contents_type %}

          {% if object|length > 0 %}
            {% if contents_type == 'produtos' %}
                {% set title = object.name %}
                {% set url = path('produto',{'slug': object.slug}) %}
                {% set url_page = path('todos') %}
                {% set image = object.image %}
                {% set id = object.id %}

            {% elseif contents_type == 'estudos-cientificos' %}
                {% set title = object.name %}
                {% set url = path('estudos-cientificos') %}
                {% set url_page = path('estudos-cientificos') %}
                {% set image = object.imageWeb %}
                {% set id = object.id %}

            {% elseif contents_type == 'cursos' %}
                {% set title = object.name %}
                {% set url = path('educacao-medica-eadbox') %}
                {% set url_page = path('educacao-medica') %}
                {% set image = object.imageWeb %}
                {% set id = object.id %}

            {% elseif contents_type == 'noticias' %}
                {% set title = object.title %}
                {% set url = path('blog_detail', {'slug': object.slug }) %}
                {% set url_page = path('noticias') %}
                {% set image = object.image %}
                {% set id = object.id %}

            {% endif %}

            {% set evaluation = evaluation(app.user, contents_type, id) %} 
            

            <div class="col-12 col-sm-4 col-md-4 col-lg-4">
              <div class="favorites">
                  <ul class="favorite-buttons">
                      <li id="limpar_filtro">
                        <a href="{{ url_page }}" >{{ contents }}</a>
                      </li>
                  </ul>
              </div>

              <article class="post-item animation-element">
                <figure>
                    <a href="{{ url }}"><img src="{{ asset('_dist/image/template/noticia-small-pic.gif') }}" alt="{{ title }}" title="{{ title }}" style="background-image:url({{ image }}); background-size:cover; background-position:center;" ></a>
                </figure>
                <div class="favorite">
                    <button data-url="{{ path('add-favorite', {'id': id, 'type': contents_type}) }}" data-i="id" class="like-button-post add-favorite">
                        {% if evaluation.id is defined and evaluation.isActive %}
                            <img class="com-favorito " src="{{ asset('_dist/image/template/with-heart.png') }}" alt="" title="">
                        {% else %}
                            <img class="sem-favorito" src="{{ asset('_dist/image/template/empty-heart.png') }}" alt="" title="">
                        {% endif %}
                    </button>
                </div>
                <h3><a href="{{ url }}">{{ title }}</a></h3>
              </article>
            </div>
          {% endif %}
      {% endfor %}
    </div>
  </div>
{% else %}
  <div class="container page-favorite">
      <div class="row">
          <h1 class="text-center">Você não possui nenhum conteúdo como favorito</h1>
      </div>
  </div>
{% endif %}
<div class="element-bottom-right paralax hidden-xs">
  <img src="{{ asset('_dist/image/template/curva-bottom-right.png') }}" alt="Bolinha" title="Bolinha">
</div>

{% endblock %}

{% block javascripts %}

{% endblock %}