src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields="email", message="Esse e-mail está sendo utilizado.")
 * @UniqueEntity(fields="username", message="Esse username está sendo utilizado.")
 */
class User implements UserInterface, \Serializable
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", nullable=true, length=100)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    // /**
    //  * @ORM\Column(type="string", length=255)
    //  */
    // private $salt;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $avatar;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_active;

 

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $last_login_at;

    /**
     * @ORM\ManyToMany(targetEntity="Role", inversedBy="users")
     */
    private $roles;

    /**
     * @ORM\OneToMany(targetEntity=UserAcess::class, mappedBy="users")
     */
    private $userAcesses;

    /**
     * @ORM\ManyToOne(targetEntity=Profile::class, inversedBy="users")
     */
    private $profile;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $crm;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $uf_crm;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $cellphone;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_resident;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $medical_center;

    /**
     * @ORM\Column(type="string", length=15, nullable=true)
     */
    private $zip_code;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=15, nullable=true)
     */
    private $number;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $complement;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $neighborhood;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $uf;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_newsletter;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_term;

    /**
     * @ORM\ManyToMany(targetEntity=Specialty::class, inversedBy="users")
     */
    private $specialty;

    /**
     * @ORM\OneToOne(targetEntity="UserNewPassword")
     *
     */
    private $newPasswordToken;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_user_old;

    /**
     * @ORM\OneToMany(targetEntity="UserFavorite", mappedBy="user")
     */
    private $favorites;

    /**
     * @ORM\OneToMany(targetEntity=UserEvents::class, mappedBy="user")
     */
    private $userEvents;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email_eadbox;

    /**
     * @ORM\OneToMany(targetEntity=UserAvaliation::class, mappedBy="user")
     */
    private $userAvaliations;

    public function __construct()
    {
        $this->roles = new ArrayCollection();
        $this->userAcesses = new ArrayCollection();
        $this->specialty = new ArrayCollection();
        $this->favorites = new ArrayCollection();
        $this->userEvents = new ArrayCollection();
        $this->userAvaliations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }
    

    public function eraseCredentials() {
        
    }

    public function serialize() {
        return serialize(array(
            $this->id,
            $this->username,
            $this->email,
            $this->password,
        ));
    }

    public function unserialize($serialized) {
        list (
            $this->id,
            $this->username,
            $this->email,
            $this->password,
            ) = unserialize($serialized, ['allowed_classes' => false]);
    }


    public function getSalt()
    {
        // you *may* need a real salt depending on your encoder
        // see section on salt below
        return null;
    }

    
    /**
     * @return Array|Role[]
     */
    public function getRoles(): array
    {
        $roles = [];
        
        foreach($this->roles as $role){
            $roles[] = $role->getRole();
        }

        return $roles;
    }

    /**
     * @return Array|Role[]
     */
    public function getRolesArray(): Array
    {
        $roles = [];
        
        foreach($this->roles as $role){
            $roles[] = $role->getRole();
        }

        return $roles;
    }

    public function addRole(Role $role): self
    {
        if (!$this->roles->contains($role)) {
            $this->roles[] = $role;
        }

        return $this;
    }

    public function removeRole(Role $role): self
    {
        if ($this->roles->contains($role)) {
            $this->roles->removeElement($role);
        }

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(string $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(bool $is_active): self
    {
        $this->is_active = $is_active;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getLastLoginAt(): ?\DateTimeInterface
    {
        return $this->last_login_at;
    }

    public function setLastLoginAt(\DateTimeInterface $last_login_at): self
    {
        $this->last_login_at = $last_login_at;

        return $this;
    }

    /**
     * @return Collection|UserAcess[]
     */
    public function getUserAcesses(): Collection
    {
        return $this->userAcesses;
    }

    public function addUserAcess(UserAcess $userAcess): self
    {
        if (!$this->userAcesses->contains($userAcess)) {
            $this->userAcesses[] = $userAcess;
            $userAcess->setUsers($this);
        }

        return $this;
    }

    public function removeUserAcess(UserAcess $userAcess): self
    {
        if ($this->userAcesses->contains($userAcess)) {
            $this->userAcesses->removeElement($userAcess);
            // set the owning side to null (unless already changed)
            if ($userAcess->getUsers() === $this) {
                $userAcess->setUsers(null);
            }
        }

        return $this;
    }

    public function getProfile(): ?Profile
    {
        return $this->profile;
    }

    public function setProfile(?Profile $profile): self
    {
        $this->profile = $profile;

        return $this;
    }

    public function getCrm(): ?string
    {
        return $this->crm;
    }

    public function setCrm(?string $crm): self
    {
        $this->crm = $crm;

        return $this;
    }

    public function getUfCrm(): ?string
    {
        return $this->uf_crm;
    }

    public function setUfCrm(?string $uf_crm): self
    {
        $this->uf_crm = $uf_crm;

        return $this;
    }

    public function getCellphone(): ?string
    {
        return $this->cellphone;
    }

    public function setCellphone(?string $cellphone): self
    {
        $this->cellphone = $cellphone;

        return $this;
    }

    public function getIsResident(): ?bool
    {
        return $this->is_resident;
    }

    public function setIsResident(?bool $is_resident): self
    {
        $this->is_resident = $is_resident;

        return $this;
    }

    public function getMedicalCenter(): ?string
    {
        return $this->medical_center;
    }

src/Controller/Front/AboutController.php
<?php

namespace App\Controller\Front;


use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Cookie;

class AboutController extends AbstractController
{
    /**
     * @Route("/quem-somos", name="quem-somos")
     */
    public function index(Request $request): Response
    {
        return $this->render('front/quem-somos/index.html.twig', []);
    }
}

src/Controller/Front/AtuacaoController.php
<?php

namespace App\Controller\Front;


use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AtuacaoController extends AbstractController
{
    /**
     * @Route("/area-de-atuacao", name="area-de-atuacao")
     */
    public function index(): Response
    {
        return $this->render('front/area-de-atuacao/index.html.twig', [
            'controller_name' => 'AtuacaoController',
        ]);
    }
}

src/Controller/Front/ContatoController.php
<?php

namespace App\Controller\Front;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use App\Entity\Contact;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;
use Symfony\Component\Mime\Address;
use Symfony\Component\Routing\Annotation\Route;

class ContatoController extends AbstractController
{
    /**
     * @Route("/contato", name="contato")
     */
    public function index(): Response
    {
        return $this->render('front/contato/index.html.twig', [
            'controller_name' => 'ContatoController',
        ]);
    }


    /**
     * @Route("/problemas-na-navegacao", name="contato_problemas")
     */
    public function contatoProblemas(Request $request, MailerInterface $mailer)
    {
        $message = null;

        if ($request->isMethod('get')) {
            return $this->render('front/contato/problemas.html.twig', [
                'status' => false,
                'message' => $message
            ]);
        }
      
        if ($request->request->get('contact')) {
            $contact = $request->request->get('contact');
            $name = isset($contact['name']) ? $contact['name'] : null;
            $ddd = isset($contact['ddd']) ? $contact['ddd'] : null;
            $phone = isset($contact['phone']) ? $contact['phone'] : null;
            $email = isset($contact['email']) ? $contact['email'] : null;
            $message = isset($contact['message']) ? $contact['message'] : null;
            
            $errors = [];

            if (!$name) {
                $errors['name'] = 'Nome é obrigatório';
            }

            if (!$ddd) {
                $errors['ddd'] = 'DDD é obrigatório';
            } else {
                // if (strlen($ddd) < 2) { //contando com as maskaras
                //     $errors['ddd'] = "Celular inválido";
                // }
            }

            if (!$phone) {
                $errors['phone'] = 'Celular é obrigatório';
            } else {
               // if ($phone) {
                                  
                    // if (strlen($phone) < 9) { //contando com as maskaras
                    //     $errors['cellphone'] = "Celular inválido";
                    // }
                //}  
            }

            if (!$email) {
                $errors['email'] = 'E-mail é obrigatório';
            }

            if (!$name) {
                $errors['message'] = 'Comentario é obrigatório';
            }

            $secret = '6LcgV24eAAAAAJUL9GHzfE6zTa1cl-cfR-HoUtO1';  // check if reCaptcha has been validated by Google     
            $captchaId = $request->request->get('g-recaptcha-response'); /** REcaptcha */
            $responseCaptcha = json_decode(file_get_contents('https://www.google.com/recaptcha/api/siteverify?secret='.$secret.'&response='.$captchaId)); //send recaptcha
            
            if ($responseCaptcha->success == true) {
                         
            } else {
               $errors['recaptcha'] = "Selecione o recaptcha é obrigatório";
            }

            //dump($errors); die();


            if (count($errors) > 0) {
                return $this->render('front/contato/problemas.html.twig', [
                    'status' => false,
                    'errors' => $errors,
                    'message' => 'Preencha os campos obrigatórios'
                ]);
            }
            
            $c = new Contact();

            $c->setName($contact['name']);
            $c->setDdd($contact['ddd']);
            $c->setPhone($contact['phone']);
            $c->setEmail($contact['email']);
            $c->setMessage($contact['message']);
            $c->setCreatedAt(new \DateTime());

            $em = $this->getDoctrine()->getManager();
            $em->persist($c);
            $em->flush();

            $response = $this->sendContact($c, $mailer, 'suporteportal@mantecorp.com.br', 'front/component/email.html.twig');
            
            if ($response) {
                $message = 'Obrigado, seu contato foi enviado com sucesso. Em breve enviaremos uma resposta.';
            }

            return $this->render('front/contato/problemas.html.twig', [
                'status' => true,
                'message' => $message
            ]);
        }
        
    }

    private function sendContact($contact, $mailer, $to,  $render)
    {


        $email = (new Email())
            ->from(new Address('portalmantecorpfarmasa@gmail.com', 'Contato Mantecorp Farmasa'))
            ->to($to)
            ->addBcc('ana.morales@cappuccinodigital.com.br')
            //->replyTo($contact->getEmail())
            ->priority(Email::PRIORITY_HIGH)
            ->subject('')
            ->html($this->renderView(
                $render,
                ['contact' => $contact]
            ));

        $mailer->send($email);
        return true;
    }
}

src/Controller/Front/DoctorsController.php
<?php

namespace App\Controller\Front;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DoctorsController extends AbstractController
{
    /**
     * @Route("/medicos/material/clg-video01", name="front_doctors")
     */
    public function index(): Response
    {
        return $this->render('front/doctors/index.html.twig', [
            'controller_name' => 'DoctorsController',
        ]);
    }
}

src/Controller/Front/NotFoundController.php
<?php

namespace App\Controller\Front;


use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class NotFoundController extends AbstractController
{
    /**
     * @Route("/404", name="404")
     */
    public function show(): Response
    {
        return $this->render('front/404/index.html.twig', [
            'controller_name' => 'NotFoundController',
        ]);
    }
}

templates/front/user/cadastro-consulta-crm.html.twig
{% extends 'front/base.html.twig' %} {% block title %}Cadastro{% endblock %} {% block body %}
<section class="page-cadastro">
    <div class="container">
        <div class="bg-top animation-element">
            <div class="bg-top-img-1 bg-top-img"></div>
            <div class="container text-center bg-top-img-main">
                <img class="" src="{{
                    asset('_dist/image/template/cadastro-pic.png') }}" alt="Mantecorp Farmasa" title="Mantecorp Farmasa">
            </div>
            <div class="bg-top-img-2 bg-top-img"></div>
        </div>
        <div class="paralax element-5 hidden-xs">
            <img src="/_dist/image/template/curva-3.png" alt="Bolinha" title="Bolinha">
        </div>
        <div class="space-h-30">
            <h1>Meu cadastro</h1>
        </div>
        <div class="register-box">
            <div class="row">
                
                <!--- cadastro etapas -->
                {{ include('front/component/cadastro-etapas.html.twig', {'step': 'cadastro-consulta-crm'}) }}

                <div class="col-12 col-sm-10 col-md-10">
                    <div class="register-content">
                        <form class="register-form" id="form">
                            
                            <div id="step1" class="step1 show">

                                <fieldset>
                                    <legend>Consultar CRM</legend>
                                    <div class="row">
                                        <div class="col-12 col-sm-4 col-md-4">
                                            <input type="hidden" name="r" />
                                            <div class="space-h-10">
                                                <label for="register-crm">CRM*: <span class="error crm-error"></span></label>
                                                <input type="text" name="crm" id="register-crm" class="register-input crm" value="{{ user_temporary.id is defined and user_temporary.crm ? user_temporary.crm : '' }}" />
                                            </div>
                                        </div>
                                        <div class="col-12 col-sm-4 col-md-2 offset-md-2">
                                            <div class="space-h-10">
                                                <label for="register-uf">UF*: <span class="error uf-crm-error"></span></label>
                                                <select name="uf_crm" id="register-uf" class="uf-crm">
                                                    {% if user_temporary.id is defined and user_temporary.ufCrm %}
                                                        <option value="{{ user_temporary.ufCrm|upper }}" selected>{{ user_temporary.ufCrm|upper }}</option>
                                                    {% endif %}
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-12 col-sm-4 col-md-4">
                                            <div class="space-h-10">
                                                <button type="button" class="btn-default btn-doctor-consultation" onclick="dataLayer.push({ 'event':'GAEvent', 'eventCategory': 'cadastro', 'eventAction': 'click', 'eventLabel': 'conultar-crm'});">Consultar CRM</button>
                                            </div>
                                        </div>
                                    </div>
                               
                                </fieldset>

                            </div>
                        
                        </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

</section>
<div class="modal register-modal" tabindex="-1" id="loading2">
    <div class="modal-dialog modal-xl">
    <div class="modal-content register-modal-loading">
        <img src="{{asset('_dist/image/template/Loading-PNG.gif')}}" alt="Loading" title="Loading" /> 
    </div>
    </div>
</div>

{% endblock %} 

{% block javascripts %}

<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.2-rc.1/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.2-rc.1/js/select2.min.js" type="text/javascript"></script>
<script src="{{ asset('vendor/jquery.mask.js') }}"></script>
<script type="text/javascript">
    $(document).ready(function() {
        //gravar dados
        $('.btn-doctor-consultation').on('click', function(e) {
            var form = $('#form')
            var crm  = $('.crm').val(), uf = $('.uf-crm').val()
            var data = {'r': true, 'crm': crm, 'uf': uf}
            
            $.ajax({
                url: "{{ path('register-doctor-consultation') }}",
                type: "POST",
                dataType: "json",
                //async: false,
                data: data,
                beforeSend: (jqXHR, settings) => {
                    $('#loading').modal('show')
                },
                success: function (data) {
                    response = data
                                        
                    if (response.status) {
                        window.location.href = response.url
                    } else {
                        
                        var message = '<ul>';

                        if (response.error.hasOwnProperty('crm')) {
                            $('.crm-error').text(response.error.crm);
                            message +=  '<li>' + response.error.crm + '</li>'
                        }

                        if (response.error.hasOwnProperty('uf_crm')) {
                            $('.uf-crm-error').text(response.error.uf_crm);
                            message +=  '<li>' + response.error.uf_crm + '</li>'
                        }

                        if (response.error.hasOwnProperty('name')) {
                            $('.name-error').text(response.error.name);
                            message +=  '<li>' + response.error.name + '</li>'
                        }
                        
                        message += '</ul>'; //end message
                        
                        $('#loading').modal('hide');

                        $('#form-notification-message').html(message);
                        $('#form-notification').modal('show');
                        
                    } 
                }
            })
        })

        $('[name="crm"]').on("keyup", function() {
            $('.crm-error').text('');
        })

        $('[name="uf_crm"]').on("change", function() {
            $('.uf-crm-error').text('');
        });
        //end

        var ufPessoal = ["", "AC", "AL", "AP", "AM", "BA", "CE", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO", "DF"];

        $("#register-uf").select2({
            data: ufPessoal
        });

        {% if user_temporary.id is defined and user_temporary.isUserOld %}
            var message = '<p>A Área Médica foi reestruturada para trazer ainda mais conteúdos para você. Para continuar navegando faça a validação do seu CRM e atualize seu cadastro.</p>'
            $('#form-notification-message').html(message);
            $('#form-notification').modal('show');
        {% endif %}
    });

    $(window).scroll(function() {
        movedToDownbyScroll('.element-5', -20);
    });
</script>
{% endblock %}

templates/front/user/cadastro-permissoes.html.twig
{% extends 'front/base.html.twig' %} {% block title %}Meu Cadastro{% endblock %} {% block body %}
<section class="page-cadastro">
    <div class="container">
        <div class="bg-top animation-element">
            <div class="bg-top-img-1 bg-top-img"></div>
            <div class="container text-center bg-top-img-main">
                <img class="" src="{{
                    asset('_dist/image/template/cadastro-pic.png') }}" alt="Mantecorp Farmasa" title="Mantecorp Farmasa">
            </div>
            <div class="bg-top-img-2 bg-top-img"></div>
        </div>
        <div class="paralax element-5 hidden-xs">
            <img src="/_dist/image/template/curva-3.png" alt="Bolinha" title="Bolinha">
        </div>
        <div class="space-h-30">
            <h1>Meu cadastro</h1>
        </div>
        <div class="register-box">
            <div class="row">

                <!--- cadastro etapas -->
                {{ include('front/component/cadastro-etapas.html.twig', {'step': 'cadastro-permissoes'}) }}

                <div class="col-12 col-sm-10 col-md-10">
                    <div class="register-content">
                        <form class="register-form" id="form">
                            <fieldset id="step2">
                                <div>
                                    <h2>Permissões</h2>
                                </div>
                                <div class="registration-form">
                                    <input type="hidden" name="r"/>
                                    <div class="form-check">
                                        <input class="form-check-input news-checked
                                            receive_news" name="is_newsletter" type="checkbox" id="flexCheckDefault" value="true" 
                                            {{ user_temporary.id is defined and user_temporary.isNewsletter ? "checked" : "" }}
                                            >
                                        <label class="form-check-label" for="flexCheckDefault">
                                            Aceito receber notícias e
                                            informações por e-mail e
                                        </label>
                                    </div>
                                    <div class="form-check">
                                        <input class="form-check-input term-checked
                                            terms_of_use" name="is_term" type="checkbox" id="flexCheckChecked" value="true"
                                            {{ user_temporary.id is defined and user_temporary.isTerm ? "checked" : "" }}
                                            >
                                        <label class="form-check-label" for="flexCheckChecked">
                                            Li e estou de acordo com os
                                            termos de uso*
                                        </label>
                                    </div>
                                    <a href="{{ path('home_termos') }}" target="_blank">Ler os termos de uso </a><span class="error is-term-error"></span>

                                </div>
                            </fieldset>
                    
                            <div class="text-center space-h-30">
                                <button type="button" class="btn-default btn-gradient btn-action">Salvar</button>
                            </div>
                        </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

</section>



{% endblock %} {% block javascripts %}

<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.2-rc.1/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.2-rc.1/js/select2.min.js" type="text/javascript"></script>
<script type="text/javascript">
    $(window).scroll(function() {
        movedToDownbyScroll('.element-5', -20);
    });

    $(document).ready(function() {
         $('.btn-action').on('click', function(e) {
            var form = $('#form')
            
            $.ajax({
                url: "{{ path('register-permissions') }}",
                type: "POST",
                dataType: "json",
                async: false,
                data: form.serialize(),
                success: function (data) {
                    response = data
                    console.log('save ', response)
                    
                    if (response.status) {
                        window.location.href = response.url
                    } else {

                        if (response.error.hasOwnProperty('is_term')) {
                            $('.is-term-error').text(response.error.is_term);
                        }
                       
                    } 
                }
            });

        })

        $('.term-checked').on("click", function(){
            if ($(this).is(':checked')) {
                $('.is-term-error').text('');
            }
        });

    });
</script>
{% endblock %}

templates/front/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello UserController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/wellington.santos2/Documents/fonts/workspace/mantecorp/mantecorp-area-medica-2021/src/Controller/Front/UserController.php'|file_link(0) }}">src/Controller/Front/UserController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/wellington.santos2/Documents/fonts/workspace/mantecorp/mantecorp-area-medica-2021/templates/front/user/index.html.twig'|file_link(0) }}">templates/front/user/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}